# Generated by Django 2.2.16 on 2020-10-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='code')),
                ('name', models.CharField(max_length=55, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'verbose_name': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('value', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Value')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='main.Currency')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rates', to='main.Currency')),
            ],
            options={
                'verbose_name_plural': 'Currency rates',
                'verbose_name': 'Currency rate',
            },
        ),
    ]
