# Generated by Django 2.2.16 on 2020-10-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyrate',
            unique_together={('base', 'target', 'date')},
        ),
    ]
